
if exist('../eigen/Eigen/Dense','file')
    disp('compiling ...');
    mex -v -I./../eigen ...
        -I./../ ...
        -I./../ASA_CG-3.0/ ...
        ../ASA_CG-3.0/asa_cg.c ../src/lbfgs.c  ...
        cppsolver.cpp  ...
        CXXFLAGS="\$CXXFLAGS -std=c++11" ...
        COPTIMFLAGS="\$COPTIMFLAGS -O2" ...
        -output cppsolver;
else
    disp('Eigen is missing');
end


